const styles: { [key: string]: React.CSSProperties } = {
  formContainer: {
    marginTop: "2rem",
    width: "100%",
    maxWidth: "700px",
    padding: "2.5rem",
    borderRadius: "16px",
    border: "1px solid rgba(0, 240, 255, 0.2)",
    boxShadow:
      "0 8px 32px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(0, 240, 255, 0.1) inset",
    backdropFilter: "blur(10px)",
    position: "relative" as const,
  },
  formRoot: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "1.75rem",
  },
  formField: {
    display: "flex",
    flexDirection: "column",
    animation: "fadeInUp 0.6s ease-out",
  },
  formLabel: {
    fontFamily: "var(--font-mono)",
    fontWeight: "bold",
    fontSize: "0.9rem",
    color: "var(--white-glow)",
    marginBottom: "0.5rem",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
  },
  input: {
    padding: "0.75rem 1rem",
    fontSize: "1rem",
    fontFamily: "var(--font-body)",
    background: "rgba(10, 14, 39, 0.6)",
    color: "var(--white-glow)",
    border: "1px solid rgba(0, 240, 255, 0.3)",
    borderRadius: "8px",
    width: "100%",
    transition: "all 0.2s ease",
    outline: "none" as const,
  },
  textarea: {
    padding: "0.75rem 1rem",
    fontSize: "1rem",
    fontFamily: "var(--font-body)",
    background: "rgba(10, 14, 39, 0.6)",
    color: "var(--white-glow)",
    border: "1px solid rgba(0, 240, 255, 0.3)",
    borderRadius: "8px",
    width: "100%",
    minHeight: "120px",
    transition: "all 0.2s ease",
    outline: "none" as const,
  },
  formSubmitButton: {
    padding: "1rem 2rem",
    fontSize: "1rem",
    fontFamily: "var(--font-mono)",
    fontWeight: "bold",
    background:
      "linear-gradient(135deg, var(--electric-cyan), var(--purple-haze))",
    color: "var(--void-black)",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    textTransform: "uppercase" as const,
    letterSpacing: "0.1em",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    boxShadow: "0 4px 20px rgba(0, 240, 255, 0.3)",
  },
  formSubmitButtonHover: {
    transform: "translateY(-2px)",
    boxShadow: "0 6px 30px rgba(0, 240, 255, 0.5)",
  },
};

export default styles;
